name: iot_gps_kucing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  get: 4.6.1
  google_maps_flutter: ^2.1.1
  input_slider: ^0.3.0
  intl: ^0.17.0
  responsive_table: ^0.2.0+2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  fonts:
    - family: Redressed
      fonts:
        - asset: assets/fonts/Redressed.ttf
  uses-material-design: true

  assets:
    - assets/images/
